In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = arr * 2
print(arr)

[ 2  4  6  8 10]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]) # 3 dimension array is tensor

print(arr)
print(type(arr))
print(arr.shape)
print(arr[0][0][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>
(3, 2, 3)
1


In [ ]:
mobno = arr[1,0,2] + arr[1,0,1]
print(mobno)

17


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) # to check dimension of arrays
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr=np.array([1,2,3,4,5,6])

print(arr[0])
print(arr[5])
print(arr[-1]) # Negative indexing
print(arr[-5])

1
6
6
2


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 15, 16]])
print(arr[1:4:2])
print(arr[:4])
print(arr[4:])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[[ 4  5  6]
 [10 15 16]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 15 16]]
[]
[[4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [10 15 16]]
[[1 2 3]
 [7 8 9]]


In [ ]:
# selecting rows and columns

print(arr[:,1])
print(arr[:,1:3])
print(arr[0:2,0:2])
print(arr[2:,0:2])

[ 2  5  8 15]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [15 16]]
[[1 2]
 [4 5]]
[[ 7  8]
 [10 15]]


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype) # to check data type


int64


In [ ]:
arr = np.array(['Red', 'Blue', 'Magenta','Purple'])

print(arr)
print(arr.dtype)
print(type(arr))

['Red' 'Blue' 'Magenta' 'Purple']
<U7
<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

arr = np.concatenate((arr1, arr2))

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # 2d
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
arr = np.array([1,2,3]) # see the issue

print(arr)
print(arr.shape)

[1 2 3]
(3,)


Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Scalar arithmetic**

Scaler is a linear algebra term means single value

In [ ]:
array = np.array([1,2,3])

print(array + 1)
print(array - 1)
print(array * 1)
print(array / 1)
print(array ** 5)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]
[  1  32 243]


**Vectorized math funcs**

it apply mathematical formula to whole array

In [ ]:
array = np.array([1.001, 2.5, 3.99])

print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
np.pi

[1.00049988 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


3.141592653589793

In [ ]:
radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


**Element Wise Arithmetic**

Mathematic fuctions

In [ ]:
ar_1d = np.arange(1,101)
print(ar_1d)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(3,12).reshape(3,3)
print(arr1)
print(arr2)
print("Addition")
print(arr1+arr2)

print("Substraction")
print(arr1-arr2)

print("Multiplication")
print(arr1*arr2)

print("Division")
print(arr1/arr2)

print("power of array1 to power of array2")
print(arr1 ** arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Addition
[[ 4  6  8]
 [10 12 14]
 [16 18 20]]
Substraction
[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]
Multiplication
[[ 3  8 15]
 [24 35 48]
 [63 80 99]]
Division
[[0.33333333 0.5        0.6       ]
 [0.66666667 0.71428571 0.75      ]
 [0.77777778 0.8        0.81818182]]
[[          1          16         243]
 [       4096       78125     1679616]
 [   40353607  1073741824 31381059609]]


**Comarison Array**

In [ ]:
scores = np.array([91,55,100,73,82,64])
print(scores)

print(scores == 100)
print(scores >= 60)
print(scores <= 60)

scores[scores < 60] = 0
print(scores)


[ 91  55 100  73  82  64]
[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]


In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array(["red","yellow","green","blue","purple","magenta"])
newarr = np.array_split(arr, 3)
print(newarr)

[array(['red', 'yellow'], dtype='<U7'), array(['green', 'blue'], dtype='<U7'), array(['purple', 'magenta'], dtype='<U7')]


You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr1 = np.array(["red","yellow","green","blue","purple","magenta","red","yellow","red"])

y=np.where(arr1 == 'red')
print(y)

(array([0, 6, 8]),)


In [ ]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array_split(a1, 3)
a2

[array([1, 2]), array([3, 4]), array([5, 6])]

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 != 1) #(arr%2 ==1)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
x = np.where(a1 == 5)
x

(array([4]),)

In [ ]:
np.random.seed(1)
arr = np.random.randint(1,50,5)
print(arr)

[38 44 13  9 10]


In [ ]:
arr = np.array([[2,2,3], [4,5,6]])
print(arr)
arr[0] = 100
print(arr)

[[2 2 3]
 [4 5 6]]
[[100 100 100]
 [  4   5   6]]


Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [ ]:
arr = np.array([3,2,0,1,5,6,7,8])

print(np.sort(arr))

[0 1 2 3 5 6 7 8]


In [ ]:
arr = np.array(['a','z','y','q','c','b']) # alphabetically sorted in ascending order

print(np.sort(arr))

['a' 'b' 'c' 'q' 'y' 'z']


Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


**Broadcasting**

It allows numpy to perform operations on array with different shapes by virtually expanding dimensions so they match the larger array's shape

The dimention have the same size
or
one of the dimention has a size of 1

In [ ]:
arar1 = np.array([[1,2,3,4]])
arar2 = np.array([[1],[2],[3],[4]])

print(arar1.shape)
print(arar2.shape)

print(arar1 + arar2)

(1, 4)
(4, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


**Aggregate functions**

summarize data and typically return a single value

In [ ]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print("Sum =",np.sum(array))
print("min =",np.min(array))
print("max =",np.max(array))
print("std =",np.std(array))
print("var =",np.var(array))
print("mean =",np.mean(array))
print("median =",np.median(array))
print("argmin =",np.argmin(array))
print("argmax =",np.argmax(array))
print("percentile 50% =",np.percentile(array,50))
print("percentile 25% =",np.percentile(array,25))
print("percentile 75% =",np.percentile(array,75))

Sum = 55
min = 1
max = 10
std = 2.8722813232690143
var = 8.25
mean = 5.5
median = 5.5
argmin = 0
argmax = 9
percentile 50% = 5.5
percentile 25% = 3.25
percentile 75% = 7.75


Sum of coulmn and rowns in array

In [ ]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

print(np.sum(array,axis=0))
print(np.sum(array,axis=1))

[ 7  9 11 13 15]
[15 40]


In [1]:
import numpy as np

In [9]:
ages = np.array([[21,17,18,20,16,30,18],
                 [39,22,15,99,18,19,20]])

teenagers = ages[ages < 18]
adults = ages[(ages > 22) & (ages <= 65)]

print(teenagers)
print(adults)

[17 16 15]
[30 39]
