## Numpy array aand basics  Learn Numpy

In [23]:
import numpy as np 

In [24]:
## creating array from list

In [25]:
arr_1d = np.array([1,2,3,4,5])
print("1D array",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array",arr_2d)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]


In [26]:
## list vs numpy array

In [27]:
py_list = [1,2,3]
print("python list multiplication", py_list * 2)

np_array = np.array([1,2,3])
print("python list multiplication", np_array * 2)

python list multiplication [1, 2, 3, 1, 2, 3]
python list multiplication [2 4 6]


In [29]:
import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n list operation time",time.time() - start)

start = time.time()
np_array = np.arange(1000000) *  2
print("\n numpy operation time",time.time() - start)


 list operation time 0.004702091217041016

 numpy operation time 0.0058405399322509766


In [30]:
## creating array from strach

In [41]:
zeros = np.zeros((3,4))
print("zeros array : \n",zeros)

ones = np.ones((2,3))
print("ones array : \n",ones)

full = np.full((2,3), 7)
print("full array : \n",full)

random = np.random.random((2,3))
print("random array : \n",random)

sequence  = np.arange(0,10,2)
print("sequence array : \n",sequence)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[7 7 7]
 [7 7 7]]
random array : 
 [[0.37299664 0.39336849 0.96418433]
 [0.8327723  0.53355936 0.98983143]]
sequence array : 
 [0 2 4 6 8]


In [37]:
##vector , matrix and tensor

In [44]:
vector = np.array([1,2,3])
print("vector : \n",vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("matrix : \n",matrix)

tensor = np.array([[[1,2], [4,5]], [[5,6], [7,8]]])
print("tensor : \n",tensor)

vector : 
 [1 2 3]
matrix : 
 [[1 2 3]
 [4 5 6]]
tensor : 
 [[[1 2]
  [4 5]]

 [[5 6]
  [7 8]]]


In [45]:
## Array properties


In [51]:
arr = np.array([[1,2,3], [4,5,'8.88']])
print("shape of array :",arr.shape)
print("dimention of array :",arr.ndim)
print("size of array :",arr.size)
print("datatype of array :",arr.dtype)

shape of array : (2, 3)
dimention of array : 2
size of array : 6
datatype of array : <U21


In [52]:
# Array Reshaping

In [66]:
arr= np.arange(12)
print("original array",arr)

reshaped = arr.reshape((4,3))
print("reshaped array",reshaped)

flattened = reshaped.flatten()
print("flatten array",flattened)

# ravel (returns view, insted of copy)
raveled = reshaped.ravel()
print("raveled array",raveled)

#transpose 
transposed = reshaped.T
print("transpose array",transposed)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
flatten array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
